#!/usr/bin/env bash

# 请使用
# `openssl rand -base64 32`
# 生成如下的值
#

function genSecrets() {
    local key="$1"
    echo "$key=$(openssl rand -hex 32)" >>env/wp_secrets.env
}

# if file exists, clear
rm -f env/wp_secrets.env

echo "# 这个文件由 wp_gen_secrets 脚本生成" >>env/wp_secrets.env
echo "# 如果您需要使用此文件请确保重新生成新的随机字符串" >>env/wp_secrets.env

genSecrets WORDPRESS_AUTH_KEY
genSecrets WORDPRESS_SECURE_AUTH_KEY
genSecrets WORDPRESS_LOGGED_IN_KEY
genSecrets WORDPRESS_NONCE_KEY
genSecrets WORDPRESS_AUTH_SALT
genSecrets WORDPRESS_SECURE_AUTH_SALT
genSecrets WORDPRESS_LOGGED_IN_SALT
genSecrets WORDPRESS_NONCE_SALT
