#!/usr/bin/env bash

set -e

if [[ ! -d "wordpress" ]]; then

    # 如果不存在则 下载 WordPress 源代码
    if [[ ! -f "wordpress.zip" ]]; then
        wget https://wordpress.org/wordpress-5.7.2.zip
    fi

    # 解压
    unzip wordpress-5.7.2.zip

    # apache is running as nobody
    chmod -R 777 wordpress
fi

# 创建 MySQL 数据文件目录
if [[ ! -d "mysql" ]]; then
    mkdir -p mysql
fi
